export const playlistResults = {
  query: "distube",
  items: [
    {
      type: "playlist",
      id: "PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
      name: "distube",
      url: "https://www.youtube.com/playlist?list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
      length: 17,
    },
    {
      type: "playlist",
      id: "PLRTLV2e_ZXmbjDnej-_gAsYPa93w3sYlr",
      name: "Distube",
      url: "https://www.youtube.com/playlist?list=PLRTLV2e_ZXmbjDnej-_gAsYPa93w3sYlr",
      length: 25,
    },
    {
      type: "playlist",
      id: "PLVdLN4Yhy71d3Nr3XXQYPsIN8m4vIej7F",
      name: "Best +100 Free Glitch Effect Footage 2021 (Noise, VHS Layer, TV Effects)",
      url: "https://www.youtube.com/playlist?list=PLVdLN4Yhy71d3Nr3XXQYPsIN8m4vIej7F",
      length: 706,
    },
    {
      type: "playlist",
      id: "PLdkO2Lq_XOx1zfzYnySSlysYv0BgW3V3l",
      name: "Distube",
      url: "https://www.youtube.com/playlist?list=PLdkO2Lq_XOx1zfzYnySSlysYv0BgW3V3l",
      length: 9,
    },
    {
      type: "playlist",
      id: "PLbLeA7W1w2T5Kg431BCMvUfTCyWfaKn4S",
      name: "Discord Music Bot Tutorial",
      url: "https://www.youtube.com/playlist?list=PLbLeA7W1w2T5Kg431BCMvUfTCyWfaKn4S",
      length: 17,
    },
    {
      type: "playlist",
      id: "PL7cOvxWH-wycFYfTcHIliPxSoRajT8FWp",
      name: "Best Disturbed Songs",
      url: "https://www.youtube.com/playlist?list=PL7cOvxWH-wycFYfTcHIliPxSoRajT8FWp",
      length: 68,
    },
    {
      type: "playlist",
      id: "PLC08AD2C2BAB0F8F6",
      name: "Disturbed youtube mix",
      url: "https://www.youtube.com/playlist?list=PLC08AD2C2BAB0F8F6",
      length: 75,
    },
    {
      type: "playlist",
      id: "PLLsdMJN8M0wQ2th-U85wwGo85a6Nm_-xi",
      name: "Shinedown, Volbeat, 5FDP, Disturbed, Godsmack, Etc",
      url: "https://www.youtube.com/playlist?list=PLLsdMJN8M0wQ2th-U85wwGo85a6Nm_-xi",
      length: 229,
    },
    {
      type: "playlist",
      id: "PLJbLehBWfm_dbUoHsMLeQBPPJXip89kyG",
      name: "디스코드 봇 만들기 (기본)",
      url: "https://www.youtube.com/playlist?list=PLJbLehBWfm_dbUoHsMLeQBPPJXip89kyG",
      length: 13,
    },
    {
      type: "playlist",
      id: "PLllWUr3O6d5g2ucR2RdIeCfK1ziYKoXJE",
      name: "Distube good",
      url: "https://www.youtube.com/playlist?list=PLllWUr3O6d5g2ucR2RdIeCfK1ziYKoXJE",
      length: 64,
    },
  ],
  results: 74,
};

export const videoResults = {
  query: "distube",
  items: [
    {
      type: "video",
      name: "Discord.js x Distube | Play, Stop, Skip Commands (Part 1) (2021+) [Episode #16]",
      id: "tbPqM6JcGA4",
      url: "https://www.youtube.com/watch?v=tbPqM6JcGA4",
      thumbnail:
        "https://i.ytimg.com/vi/tbPqM6JcGA4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBGzjqv86A0ml10BXDIVWiTQhhyPQ",
      isLive: false,
      author: {
        name: "CougHyyee",
        channelID: "UCnkI1CiXpdQeibcwtCtVvIQ",
        url: "https://www.youtube.com/channel/UCnkI1CiXpdQeibcwtCtVvIQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 1710,
      duration: "16:44",
      uploadedAt: "3 months ago",
    },
    {
      type: "video",
      name: "Discord.js (v12) BOT | Most easiest Music Bot | filters, seek, play, skip, stop | distube | 1/3",
      id: "lzZU-8FU2wQ",
      url: "https://www.youtube.com/watch?v=lzZU-8FU2wQ",
      thumbnail:
        "https://i.ytimg.com/vi/lzZU-8FU2wQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD3pBo_uShS_7KuxFy3phF3xx-edw",
      isLive: false,
      author: {
        name: "Tomato6966",
        channelID: "UC1AgotpFHNhzolUtAjPgZqQ",
        url: "https://www.youtube.com/channel/UC1AgotpFHNhzolUtAjPgZqQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLSNDx98wsvw3WTJHaZs2NCCQTGFl1KC0xautdSDdA=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLSNDx98wsvw3WTJHaZs2NCCQTGFl1KC0xautdSDdA=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 4030,
      duration: "1:10:25",
      uploadedAt: "7 months ago",
    },
    {
      type: "video",
      name: "Disturbed - Stricken [Video]",
      id: "I77mjesUbkw",
      url: "https://www.youtube.com/watch?v=I77mjesUbkw",
      thumbnail:
        "https://i.ytimg.com/vi/I77mjesUbkw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAaztN4uv4H9-Bnw5G0XHaicLZgmg",
      isLive: false,
      author: {
        name: "Disturbed",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 56632348,
      duration: "4:11",
      uploadedAt: "11 years ago",
    },
    {
      type: "video",
      name: "Disturbed - Down With The Sickness [Official Music Video]",
      id: "09LTT0xwdfw",
      url: "https://www.youtube.com/watch?v=09LTT0xwdfw",
      thumbnail:
        "https://i.ytimg.com/vi/09LTT0xwdfw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCPFLfKQZ6EILrXEiox5oMcaxvFow",
      isLive: false,
      author: {
        name: "Disturbed",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 137706960,
      duration: "3:37",
      uploadedAt: "11 years ago",
    },
    {
      type: "video",
      name: "Discord.js x Distube | Queue & Skip Commands (Part 2) (2021+) [Episode #16]",
      id: "ylXL2Grsplc",
      url: "https://www.youtube.com/watch?v=ylXL2Grsplc",
      thumbnail:
        "https://i.ytimg.com/vi/ylXL2Grsplc/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDZ1WslIzG7iR9uYw1qftQJGz_dVA",
      isLive: false,
      author: {
        name: "CougHyyee",
        channelID: "UCnkI1CiXpdQeibcwtCtVvIQ",
        url: "https://www.youtube.com/channel/UCnkI1CiXpdQeibcwtCtVvIQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 718,
      duration: "8:08",
      uploadedAt: "2 months ago",
    },
    {
      type: "video",
      name: "[NEW] DISCORD.JS MUSIC BOT! (UPDATED)",
      id: "Zxx0AQZ29lM",
      url: "https://www.youtube.com/watch?v=Zxx0AQZ29lM",
      thumbnail:
        "https://i.ytimg.com/vi/Zxx0AQZ29lM/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB4t_w4uOQOVPq6d31aV62pFxru6Q",
      isLive: false,
      author: {
        name: "DashCruft",
        channelID: "UCGfLATfpHApnScvMr9dXd1g",
        url: "https://www.youtube.com/channel/UCGfLATfpHApnScvMr9dXd1g",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLT6iwnUfxrXKrzPgfYEk9H-1K5ALj6Wr8IFnxvOKw=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLT6iwnUfxrXKrzPgfYEk9H-1K5ALj6Wr8IFnxvOKw=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 32245,
      duration: "13:31",
      uploadedAt: "5 months ago",
    },
    {
      type: "video",
      name: "How to setup DisTube bot discord very easily on your discord server | Music & Fun",
      id: "oqpgPWSOHdM",
      url: "https://www.youtube.com/watch?v=oqpgPWSOHdM",
      thumbnail:
        "https://i.ytimg.com/vi/oqpgPWSOHdM/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBIDFAniSRLG21ux0JjNek6DEMHMw",
      isLive: false,
      author: {
        name: "Roduz",
        channelID: "UCjnUiHCUWjwx_cizD4JYpjQ",
        url: "https://www.youtube.com/channel/UCjnUiHCUWjwx_cizD4JYpjQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLSDlEFv1TLkFq47l2X3_I2D1koTry6BKI35TmmH=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLSDlEFv1TLkFq47l2X3_I2D1koTry6BKI35TmmH=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 1061,
      duration: "8:09",
      uploadedAt: "5 months ago",
    },
    {
      type: "video",
      name: "Distube Music Bot ytdl-core Status Code 404 ,429 Error Fixed  | Advance Discord Distube Music Bot",
      id: "9bZGT9frKLw",
      url: "https://www.youtube.com/watch?v=9bZGT9frKLw",
      thumbnail:
        "https://i.ytimg.com/vi/9bZGT9frKLw/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCk5S5xyFVReGcCdPV_gDPK60lUMQ",
      isLive: false,
      author: {
        name: "Tech Boy Gaming",
        channelID: "UCINCfgiBYCykOemiuVhqtIQ",
        url: "https://www.youtube.com/channel/UCINCfgiBYCykOemiuVhqtIQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLScR4eUWjJt0bHTftgQ_lf7skYCWulN-Jh-3BtXQQ=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLScR4eUWjJt0bHTftgQ_lf7skYCWulN-Jh-3BtXQQ=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 949,
      duration: "7:36",
      uploadedAt: "2 weeks ago",
    },
    {
      type: "video",
      name: "How to setup PyQuantum giveaway feature in Discord | Distube | Bot Setup #2",
      id: "eBgS5KgxA1E",
      url: "https://www.youtube.com/watch?v=eBgS5KgxA1E",
      thumbnail:
        "https://i.ytimg.com/vi/eBgS5KgxA1E/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA-8FbPrnnCu3bTYclM3vscU37xqQ",
      isLive: false,
      author: {
        name: "Distube ",
        channelID: "UCaD6sK5RA_8dLuMoD22Xs0A",
        url: "https://www.youtube.com/channel/UCaD6sK5RA_8dLuMoD22Xs0A",
        bestAvatar: {
          url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 188,
      duration: "2:29",
      uploadedAt: "3 weeks ago",
    },
    {
      type: "video",
      name: "How to setup Server Stats bot in Discord | Distube | Bot Setup #1",
      id: "G8jz3tmGznE",
      url: "https://www.youtube.com/watch?v=G8jz3tmGznE",
      thumbnail:
        "https://i.ytimg.com/vi/G8jz3tmGznE/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCs-T5gu7Kyb_DFe-7fe3zB3ZP1SQ",
      isLive: false,
      author: {
        name: "Distube ",
        channelID: "UCaD6sK5RA_8dLuMoD22Xs0A",
        url: "https://www.youtube.com/channel/UCaD6sK5RA_8dLuMoD22Xs0A",
        bestAvatar: {
          url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 56,
      duration: "2:27",
      uploadedAt: "3 weeks ago",
    },
  ],
  results: 2420,
};
