export const firstPlaylistInfo = {
  id: "PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
  thumbnail: {
    url: "https://i.ytimg.com/vi/3moLkjvhEu0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA14XKyrORIifS-TIjf9cu1Z8hDPA",
    width: 336,
    height: 188,
  },
  url: "https://www.youtube.com/playlist?list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
  title: "distube",
  total_items: 17,
  views: 1676,
  items: [
    {
      title: "Disturbed - Stricken [Official Music Video]",
      id: "3moLkjvhEu0",
      shortUrl: "https://www.youtube.com/watch?v=3moLkjvhEu0",
      url: "https://www.youtube.com/watch?v=3moLkjvhEu0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=1",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/3moLkjvhEu0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB2iwHMKdR4SeKViqLx-UR9HwOFUw",
      isLive: false,
      duration: "4:11",
    },
    {
      title: "Disturbed - Down With The Sickness [Official Music Video]",
      id: "09LTT0xwdfw",
      shortUrl: "https://www.youtube.com/watch?v=09LTT0xwdfw",
      url: "https://www.youtube.com/watch?v=09LTT0xwdfw&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=2",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/09LTT0xwdfw/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBYSeu3wpE9Ln744sGFrEYxS7lHDw",
      isLive: false,
      duration: "3:37",
    },
    {
      title: "Disturbed - Stupify [Official Music Video]",
      id: "GVcY--XzeIc",
      shortUrl: "https://www.youtube.com/watch?v=GVcY--XzeIc",
      url: "https://www.youtube.com/watch?v=GVcY--XzeIc&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=3",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/GVcY--XzeIc/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBIR2I-rPAgACGifAg7_9wwmIuyWA",
      isLive: false,
      duration: "4:07",
    },
    {
      title: "Godsmack - I Stand Alone (Official Music Video)",
      id: "OYjZK_6i37M",
      shortUrl: "https://www.youtube.com/watch?v=OYjZK_6i37M",
      url: "https://www.youtube.com/watch?v=OYjZK_6i37M&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=4",
      author: {
        url: "https://www.youtube.com/channel/UCe9rl8k6yymUeVzzXfFGWwA",
        channelID: "UCe9rl8k6yymUeVzzXfFGWwA",
        name: "Godsmack",
      },
      thumbnail:
        "https://i.ytimg.com/vi/OYjZK_6i37M/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCTJhGi36XXmWuxkWFTCIERq_4zrw",
      isLive: false,
      duration: "4:56",
    },
    {
      title: "System Of A Down - B.Y.O.B. (Official Video)",
      id: "zUzd9KyIDrM",
      shortUrl: "https://www.youtube.com/watch?v=zUzd9KyIDrM",
      url: "https://www.youtube.com/watch?v=zUzd9KyIDrM&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=5",
      author: {
        url: "https://www.youtube.com/channel/UC7-YMmnc0ppcWmio8t1WdcA",
        channelID: "UC7-YMmnc0ppcWmio8t1WdcA",
        name: "System Of A Down",
      },
      thumbnail:
        "https://i.ytimg.com/vi/zUzd9KyIDrM/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAsxmHhtE691Sh76BsF957tq-yuqg",
      isLive: false,
      duration: "4:23",
    },
    {
      title: "System Of A Down - Chop Suey! (Official Video)",
      id: "CSvFpBOe8eY",
      shortUrl: "https://www.youtube.com/watch?v=CSvFpBOe8eY",
      url: "https://www.youtube.com/watch?v=CSvFpBOe8eY&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=6",
      author: {
        url: "https://www.youtube.com/channel/UC7-YMmnc0ppcWmio8t1WdcA",
        channelID: "UC7-YMmnc0ppcWmio8t1WdcA",
        name: "System Of A Down",
      },
      thumbnail:
        "https://i.ytimg.com/vi/CSvFpBOe8eY/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBGntrlv7yGSQfPdN4bXXTUMFUxiQ",
      isLive: false,
      duration: "3:27",
    },
    {
      title: "Drowning Pool - Bodies",
      id: "04F4xlWSFh0",
      shortUrl: "https://www.youtube.com/watch?v=04F4xlWSFh0",
      url: "https://www.youtube.com/watch?v=04F4xlWSFh0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=7",
      author: {
        url: "https://www.youtube.com/channel/UCRFHKKNGdaIs9NaULSUuKGw",
        channelID: "UCRFHKKNGdaIs9NaULSUuKGw",
        name: "Drowning Pool",
      },
      thumbnail:
        "https://i.ytimg.com/vi/04F4xlWSFh0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCrnDKQ4Rfqnx9qt6FrK9FzxznshQ",
      isLive: false,
      duration: "3:40",
    },
    {
      title: "Drowning Pool - Step Up",
      id: "Co5n2RVbWM0",
      shortUrl: "https://www.youtube.com/watch?v=Co5n2RVbWM0",
      url: "https://www.youtube.com/watch?v=Co5n2RVbWM0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=8",
      author: {
        url: "https://www.youtube.com/channel/UCRFHKKNGdaIs9NaULSUuKGw",
        channelID: "UCRFHKKNGdaIs9NaULSUuKGw",
        name: "Drowning Pool",
      },
      thumbnail:
        "https://i.ytimg.com/vi/Co5n2RVbWM0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB3rdoqRQ8Nno9nXK8B8epUFiMxRQ",
      isLive: false,
      duration: "3:23",
    },
    {
      title: "Disturbed - down with the sickness",
      id: "L78yVFeyvRo",
      shortUrl: "https://www.youtube.com/watch?v=L78yVFeyvRo",
      url: "https://www.youtube.com/watch?v=L78yVFeyvRo&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=9",
      author: {
        url: "https://www.youtube.com/user/xJuliiaJewelx",
        channelID: "UCIG-qQkc8nrazBcLPIrbTPA",
        name: "xJuliiaJewelx",
      },
      thumbnail:
        "https://i.ytimg.com/vi/L78yVFeyvRo/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDadTqyq2Q_bt9_8An8XnjsZLbFPQ",
      isLive: false,
      duration: "4:39",
    },
    {
      title: "stupify - disturbed",
      id: "CQBNH3UFEC0",
      shortUrl: "https://www.youtube.com/watch?v=CQBNH3UFEC0",
      url: "https://www.youtube.com/watch?v=CQBNH3UFEC0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=10",
      author: {
        url: "https://www.youtube.com/user/disturbedrocka",
        channelID: "UC-aNyA0-LT96awZKERYCTRQ",
        name: "disturbedrocka",
      },
      thumbnail:
        "https://i.ytimg.com/vi/CQBNH3UFEC0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDymt-BEQ1pPCkJKvOcjTWfu6I2Sg",
      isLive: false,
      duration: "4:35",
    },
    {
      title: "Limp Bizkit - Break Stuff",
      id: "ZpUYjpKg9KY",
      shortUrl: "https://www.youtube.com/watch?v=ZpUYjpKg9KY",
      url: "https://www.youtube.com/watch?v=ZpUYjpKg9KY&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=11",
      author: {
        url: "https://www.youtube.com/channel/UCCndqRyI-5Zl8Mutlq71ASw",
        channelID: "UCCndqRyI-5Zl8Mutlq71ASw",
        name: "limpbizkit",
      },
      thumbnail:
        "https://i.ytimg.com/vi/ZpUYjpKg9KY/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBqjo0H2NzhILiA5XmtJlDw-6RuMg",
      isLive: false,
      duration: "2:50",
    },
    {
      title: "Limp Bizkit - Faith",
      id: "l-EdCNjumvI",
      shortUrl: "https://www.youtube.com/watch?v=l-EdCNjumvI",
      url: "https://www.youtube.com/watch?v=l-EdCNjumvI&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=12",
      author: {
        url: "https://www.youtube.com/channel/UCCndqRyI-5Zl8Mutlq71ASw",
        channelID: "UCCndqRyI-5Zl8Mutlq71ASw",
        name: "limpbizkit",
      },
      thumbnail:
        "https://i.ytimg.com/vi/l-EdCNjumvI/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAUrzUryFQPf2HdMurxsoGwzLybLQ",
      isLive: false,
      duration: "2:45",
    },
    {
      title: "Limp Bizkit- jump around",
      id: "UI-jNetj9t0",
      shortUrl: "https://www.youtube.com/watch?v=UI-jNetj9t0",
      url: "https://www.youtube.com/watch?v=UI-jNetj9t0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=13",
      author: {
        url: "https://www.youtube.com/user/bobeen17",
        channelID: "UClDFSTgkAUvaHnvv-qw9vzw",
        name: "bobeen17",
      },
      thumbnail:
        "https://i.ytimg.com/vi/UI-jNetj9t0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCdU7MOvU96HkOY15i9Zid2aq7JUw",
      isLive: false,
      duration: "2:46",
    },
    {
      title: "Slipknot - Psychosocial [OFFICIAL VIDEO]",
      id: "5abamRO41fE",
      shortUrl: "https://www.youtube.com/watch?v=5abamRO41fE",
      url: "https://www.youtube.com/watch?v=5abamRO41fE&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=14",
      author: {
        url: "https://www.youtube.com/channel/UCOJZ1tna8yj8mAEITPkHNCQ",
        channelID: "UCOJZ1tna8yj8mAEITPkHNCQ",
        name: "Slipknot",
      },
      thumbnail:
        "https://i.ytimg.com/vi/5abamRO41fE/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBeLRAt_djqKyYG9jv-vniKG-27-g",
      isLive: false,
      duration: "5:03",
    },
    {
      title: "Disturbed - Another Way To Die [Official Music Video]",
      id: "HwELajFteTo",
      shortUrl: "https://www.youtube.com/watch?v=HwELajFteTo",
      url: "https://www.youtube.com/watch?v=HwELajFteTo&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=15",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/HwELajFteTo/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAcbMwxa_WV95kQB4Kzqo-W-vZqyw",
      isLive: false,
      duration: "4:15",
    },
    {
      title: "A'lure Girls - ผักบุ้ง [HD]",
      id: "4B7H6zaeOzw",
      shortUrl: "https://www.youtube.com/watch?v=4B7H6zaeOzw",
      url: "https://www.youtube.com/watch?v=4B7H6zaeOzw&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=16",
      author: {
        url: "https://www.youtube.com/user/VertexClub7",
        channelID: "UC0qtGtAqSCgmkZFV3-5uWyA",
        name: "Movie Reac",
      },
      thumbnail:
        "https://i.ytimg.com/vi/4B7H6zaeOzw/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBFrToXZBo1cAOKFu5DKAOtsBkSwQ",
      isLive: false,
      duration: "4:01",
    },
  ],
};

export const playlistResults = {
  query: "distube",
  items: [
    {
      type: "playlist" as const,
      id: "PLbLeA7W1w2T5Kg431BCMvUfTCyWfaKn4S",
      name: "Discord Music Bot Tutorial",
      url: "https://www.youtube.com/playlist?list=PLbLeA7W1w2T5Kg431BCMvUfTCyWfaKn4S",
      owner: {
        name: "Tomato6966",
        channelID: "UC1AgotpFHNhzolUtAjPgZqQ",
        url: "https://www.youtube.com/c/Tomato6966",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 17,
    },
    {
      type: "playlist" as const,
      id: "PLllWUr3O6d5g2ucR2RdIeCfK1ziYKoXJE",
      name: "Distube good",
      url: "https://www.youtube.com/playlist?list=PLllWUr3O6d5g2ucR2RdIeCfK1ziYKoXJE",
      owner: {
        name: "William Brady",
        channelID: "UCZtrNv8Y2bGLrX-2CUwSRkQ",
        url: "https://www.youtube.com/channel/UCZtrNv8Y2bGLrX-2CUwSRkQ",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 69,
    },
    {
      type: "playlist" as const,
      id: "PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
      name: "distube",
      url: "https://www.youtube.com/playlist?list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
      owner: {
        name: "Thanakorn Rommayanont",
        channelID: "UCYlUOETzzVxRud28z3Nj1NQ",
        url: "https://www.youtube.com/channel/UCYlUOETzzVxRud28z3Nj1NQ",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 17,
    },
    {
      type: "playlist" as const,
      id: "PLdkO2Lq_XOx1zfzYnySSlysYv0BgW3V3l",
      name: "Distube",
      url: "https://www.youtube.com/playlist?list=PLdkO2Lq_XOx1zfzYnySSlysYv0BgW3V3l",
      owner: {
        name: "End Wood",
        channelID: "UCjdhsUd7lXIZN_0wFwj-Vhg",
        url: "https://www.youtube.com/c/EndWoodie",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 10,
    },
    {
      type: "playlist" as const,
      id: "PLfX3HOwW2vw-_G-0M3IaqlX1YsFDLRGAK",
      name: "Distube",
      url: "https://www.youtube.com/playlist?list=PLfX3HOwW2vw-_G-0M3IaqlX1YsFDLRGAK",
      owner: {
        name: "bach bacharo",
        channelID: "UC7QTTzGagzeg_Qt59CHr4aQ",
        url: "https://www.youtube.com/channel/UC7QTTzGagzeg_Qt59CHr4aQ",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 12,
    },
    {
      type: "playlist" as const,
      id: "PL2XgzC2wvcwDp0RP5L2ii5fqbJXOl16WX",
      name: "do not distube",
      url: "https://www.youtube.com/playlist?list=PL2XgzC2wvcwDp0RP5L2ii5fqbJXOl16WX",
      owner: {
        name: "branden ellison",
        channelID: "UCyucS51VsV3sJ2lBZzmM_Og",
        url: "https://www.youtube.com/channel/UCyucS51VsV3sJ2lBZzmM_Og",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 9,
    },
    {
      type: "playlist" as const,
      id: "PL4LQxial9rJyHgzcho4gDJrxtEy_5onNa",
      name: "Distube",
      url: "https://www.youtube.com/playlist?list=PL4LQxial9rJyHgzcho4gDJrxtEy_5onNa",
      owner: {
        name: "Dirk Buetow",
        channelID: "UCpODmX9cBFlBRiEnqbMemuA",
        url: "https://www.youtube.com/channel/UCpODmX9cBFlBRiEnqbMemuA",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 8,
    },
    {
      type: "playlist" as const,
      id: "PL4aKfCDZzyhQyGM0B2kxDlYrFib-MrhIa",
      name: "dis tube",
      url: "https://www.youtube.com/playlist?list=PL4aKfCDZzyhQyGM0B2kxDlYrFib-MrhIa",
      owner: {
        name: "J L",
        channelID: "UC93aMBtWU8jN3Kb855pQWZQ",
        url: "https://www.youtube.com/channel/UC93aMBtWU8jN3Kb855pQWZQ",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 11,
    },
    {
      type: "playlist" as const,
      id: "PLF49BB009EB0D39B9",
      name: "distubing",
      url: "https://www.youtube.com/playlist?list=PLF49BB009EB0D39B9",
      owner: {
        name: "7G06",
        channelID: "UC_3eSlr019IydseglwTZuKQ",
        url: "https://www.youtube.com/c/7G06",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 7,
    },
    {
      type: "playlist" as const,
      id: "PLiRL7CfiWlYHmWIr1JH4CzFudqisog5oj",
      name: "Distributed Systems",
      url: "https://www.youtube.com/playlist?list=PLiRL7CfiWlYHmWIr1JH4CzFudqisog5oj",
      owner: {
        name: "Hicham Elmongui",
        channelID: "UC1gu4NqQ9uvmnVR7kvYFrJw",
        url: "https://www.youtube.com/user/elmongui76",
        ownerBadges: [],
        verified: false,
      },
      publishedAt: "",
      length: 11,
    },
  ],
  results: 366,
};

export const videoResults = {
  query: "distube",
  items: [
    {
      type: "video" as const,
      name: "How to setup DisTube bot discord very easily on your discord server | Music & Fun",
      id: "oqpgPWSOHdM",
      url: "https://www.youtube.com/watch?v=oqpgPWSOHdM",
      thumbnail:
        "https://i.ytimg.com/vi/oqpgPWSOHdM/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBIDFAniSRLG21ux0JjNek6DEMHMw",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/oqpgPWSOHdM/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBIDFAniSRLG21ux0JjNek6DEMHMw",
          width: 480,
          height: 270,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Roduz",
        channelID: "UCjnUiHCUWjwx_cizD4JYpjQ",
        url: "https://www.youtube.com/c/Roduz",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLSDlEFv1TLkFq47l2X3_I2D1koTry6BKI35TmmH=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLSDlEFv1TLkFq47l2X3_I2D1koTry6BKI35TmmH=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: "",
      views: 10521,
      duration: "8:09",
      uploadedAt: "1 year ago",
    },
    {
      type: "video" as const,
      name: "Disturbed - Down With The Sickness [Official Music Video]",
      id: "09LTT0xwdfw",
      url: "https://www.youtube.com/watch?v=09LTT0xwdfw",
      thumbnail:
        "https://i.ytimg.com/vi/09LTT0xwdfw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCPFLfKQZ6EILrXEiox5oMcaxvFow",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/09LTT0xwdfw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCPFLfKQZ6EILrXEiox5oMcaxvFow",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/09LTT0xwdfw/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDY88jNr6M7sL6AWwfLRUYnNLvkAQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Disturbed",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLTPrsCDm1dJbYXzadYU2WrAGaLYzd51qZqa41R_=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLTPrsCDm1dJbYXzadYU2WrAGaLYzd51qZqa41R_=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: "",
      views: 161395588,
      duration: "3:37",
      uploadedAt: "12 years ago",
    },
    {
      type: "video" as const,
      name: "Disturbed - Stricken [Video]",
      id: "I77mjesUbkw",
      url: "https://www.youtube.com/watch?v=I77mjesUbkw",
      thumbnail:
        "https://i.ytimg.com/vi/I77mjesUbkw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAaztN4uv4H9-Bnw5G0XHaicLZgmg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/I77mjesUbkw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAaztN4uv4H9-Bnw5G0XHaicLZgmg",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/I77mjesUbkw/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAYWGAF3nuDrM0NAjEInWvCQ-1IpQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Disturbed",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLTPrsCDm1dJbYXzadYU2WrAGaLYzd51qZqa41R_=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLTPrsCDm1dJbYXzadYU2WrAGaLYzd51qZqa41R_=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: "",
      views: 68557519,
      duration: "4:11",
      uploadedAt: "12 years ago",
    },
    {
      type: "video" as const,
      name: "How To Set Up DISTUBE THE DISCORD BOT AND USE",
      id: "K2NaqO6q1Ug",
      url: "https://www.youtube.com/watch?v=K2NaqO6q1Ug",
      thumbnail:
        "https://i.ytimg.com/vi/K2NaqO6q1Ug/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDSI-ERMW5lS1yLp6oyoFN8T0ezDg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/K2NaqO6q1Ug/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDSI-ERMW5lS1yLp6oyoFN8T0ezDg",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/K2NaqO6q1Ug/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDG-CTMgtPP9mrND0HzlSs_A3eqUQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "DZ Gaming™",
        channelID: "UCBCsVaoH2GERmw3tG5RnCoA",
        url: "https://www.youtube.com/c/DZGamingTM",
        bestAvatar: {
          url: "https://yt3.ggpht.com/TaFrnP5c7L3W-gasOSm8lubulXmsJkY1dRMqTyOKJyVpKXrVU9F16cKuqADRXWBpuBGJaDUB_g4=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/TaFrnP5c7L3W-gasOSm8lubulXmsJkY1dRMqTyOKJyVpKXrVU9F16cKuqADRXWBpuBGJaDUB_g4=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: "",
      views: 1061,
      duration: "11:54",
      uploadedAt: "7 months ago",
    },
    {
      type: "video" as const,
      name: "Poner MÚSICA en DISCORD - Bot DisTube",
      id: "zSqXTQLxvII",
      url: "https://www.youtube.com/watch?v=zSqXTQLxvII",
      thumbnail:
        "https://i.ytimg.com/vi/zSqXTQLxvII/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDsmh1MV-8zKM8tp7dwFPzb4rN_TQ",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/zSqXTQLxvII/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDsmh1MV-8zKM8tp7dwFPzb4rN_TQ",
          width: 480,
          height: 270,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Tuto Discord",
        channelID: "UClIiGWJjW17_yszdChIM87g",
        url: "https://www.youtube.com/c/TutoDiscord",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLSqpnFkbwuBaBnIUCjhinF2EZx3d-2CPDlNsfAx7w=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLSqpnFkbwuBaBnIUCjhinF2EZx3d-2CPDlNsfAx7w=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: "",
      views: 7345,
      duration: "5:30",
      uploadedAt: "6 months ago",
    },
    {
      type: "video" as const,
      name: "Disturbed - Prayer [Official Music Video]",
      id: "DWSlOCEzRGo",
      url: "https://www.youtube.com/watch?v=DWSlOCEzRGo",
      thumbnail:
        "https://i.ytimg.com/vi/DWSlOCEzRGo/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCr8c-JKZPs9Eocev8UluaHrL6_2A",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/DWSlOCEzRGo/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCr8c-JKZPs9Eocev8UluaHrL6_2A",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/DWSlOCEzRGo/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCysl4WW_KMvXrYEUMwGZMc502Nnw",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Disturbed",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLTPrsCDm1dJbYXzadYU2WrAGaLYzd51qZqa41R_=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLTPrsCDm1dJbYXzadYU2WrAGaLYzd51qZqa41R_=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: "",
      views: 39998435,
      duration: "3:45",
      uploadedAt: "12 years ago",
    },
    {
      type: "video" as const,
      name: "Discord.js x Distube | Play, Stop, Skip Commands (Part 1) (2021+) [Episode #16]",
      id: "tbPqM6JcGA4",
      url: "https://www.youtube.com/watch?v=tbPqM6JcGA4",
      thumbnail:
        "https://i.ytimg.com/vi/tbPqM6JcGA4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBGzjqv86A0ml10BXDIVWiTQhhyPQ",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/tbPqM6JcGA4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBGzjqv86A0ml10BXDIVWiTQhhyPQ",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/tbPqM6JcGA4/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBIfdmC0XBstgiFdVm_HEOpiz4VPQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Cough Codes",
        channelID: "UCnkI1CiXpdQeibcwtCtVvIQ",
        url: "https://www.youtube.com/channel/UCnkI1CiXpdQeibcwtCtVvIQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: "",
      views: 7762,
      duration: "16:44",
      uploadedAt: "1 year ago",
    },
    {
      type: "video" as const,
      name: "El Mejor Bot De Música Discord 2022",
      id: "xFhpiT5Ug2E",
      url: "https://www.youtube.com/watch?v=xFhpiT5Ug2E",
      thumbnail:
        "https://i.ytimg.com/vi/xFhpiT5Ug2E/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLByrtS41W_GxzLNnon3fYuXIqMkbw",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/xFhpiT5Ug2E/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLByrtS41W_GxzLNnon3fYuXIqMkbw",
          width: 480,
          height: 270,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Discord Tutoriales",
        channelID: "UCd9O7gMjc_m7GKHkVN4AYoQ",
        url: "https://www.youtube.com/c/DiscordTutoriales",
        bestAvatar: {
          url: "https://yt3.ggpht.com/0tFErRKzPjU-CUxZd8KPcHXR0Tva_0RVbo7g__LhJcyqPwS6-bY5qGEC-_c2J3Bn1xom-_TU=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/0tFErRKzPjU-CUxZd8KPcHXR0Tva_0RVbo7g__LhJcyqPwS6-bY5qGEC-_c2J3Bn1xom-_TU=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: "",
      views: 43238,
      duration: "8:39",
      uploadedAt: "4 months ago",
    },
    {
      type: "video" as const,
      name: "Complete Music System | Discord.JS V13 Series | #14",
      id: "qP1LIkGoNX4",
      url: "https://www.youtube.com/watch?v=qP1LIkGoNX4",
      thumbnail:
        "https://i.ytimg.com/vi/qP1LIkGoNX4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCpv0RpPXSuN_uGCaYI31sG2NhFlQ",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/qP1LIkGoNX4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCpv0RpPXSuN_uGCaYI31sG2NhFlQ",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/qP1LIkGoNX4/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBx--wFOMQlr0urPQl-L3Mj7P1_dQ",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Lyxcode",
        channelID: "UCGyqi4UW3on0jK1W5reea1w",
        url: "https://www.youtube.com/c/Lyxcode",
        bestAvatar: {
          url: "https://yt3.ggpht.com/_3kt3ilJer5yO-KQqMjWizl3OqhDymwPaETJ5y41a2Cc_xfbtTPpvabUD_HVcPSl_0KL6ZbyQA=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/_3kt3ilJer5yO-KQqMjWizl3OqhDymwPaETJ5y41a2Cc_xfbtTPpvabUD_HVcPSl_0KL6ZbyQA=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: "",
      views: 19014,
      duration: "32:12",
      uploadedAt: "7 months ago",
    },
    {
      type: "video" as const,
      name: "Discord.js V13 #5 DISTUBE",
      id: "7l2qXRtmdho",
      url: "https://www.youtube.com/watch?v=7l2qXRtmdho",
      thumbnail:
        "https://i.ytimg.com/vi/7l2qXRtmdho/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAN28jFogCF-9mpyEWitpVSNCFvRg",
      thumbnails: [
        {
          url: "https://i.ytimg.com/vi/7l2qXRtmdho/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAN28jFogCF-9mpyEWitpVSNCFvRg",
          width: 720,
          height: 404,
        },
        {
          url: "https://i.ytimg.com/vi/7l2qXRtmdho/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBwgROz1bYr11DrTrACsAno26KrTg",
          width: 360,
          height: 202,
        },
      ],
      isUpcoming: false,
      upcoming: null,
      isLive: false,
      badges: [],
      author: {
        name: "Cyber Tutorials",
        channelID: "UCKTzi3R-yQEvkEgxGDhfLxQ",
        url: "https://www.youtube.com/channel/UCKTzi3R-yQEvkEgxGDhfLxQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/hPi6XszmU2K1x5ADyE5RukPOh8iQFaLhqHxjdH4l37avg5UXbuTMLGqw0TnDjkBvY6u5f7Jzkg=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/hPi6XszmU2K1x5ADyE5RukPOh8iQFaLhqHxjdH4l37avg5UXbuTMLGqw0TnDjkBvY6u5f7Jzkg=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
        verified: false,
      },
      description: "",
      views: 649,
      duration: "38:40",
      uploadedAt: "7 months ago",
    },
  ],
  results: 8447,
};
