export const rawClientUser = {
  verified: true,
  username: "Test",
  mfa_enabled: true,
  id: "732441066992566304",
  flags: 0,
  discriminator: "0000",
  bot: true,
  avatar: "",
};

export const rawGuild = {
  member_count: 15,
  preferred_locale: "en-US",
  stage_instances: [],
  stickers: [],
  voice_states: [],
  icon: "",
  application_command_count: 89,
  afk_channel_id: null,
  mfa_level: 0,
  unavailable: false,
  large: false,
  system_channel_flags: 0,
  vanity_url_code: null,
  verification_level: 1,
  public_updates_channel_id: "835876744317108254",
  max_video_channel_users: 25,
  name: "Test",
  rules_channel_id: "835876743847739454",
  channels: [
    {
      type: 0,
      topic: null,
      rate_limit_per_user: 0,
      position: 3,
      permission_overwrites: [],
      parent_id: "737499503384461323",
      nsfw: false,
      name: "text",
      last_message_id: "863623849421963284",
      id: "737499503384461325",
    },
    {
      user_limit: 10000,
      type: 13,
      topic: null,
      rtc_region: null,
      position: 0,
      permission_overwrites: [],
      parent_id: "737499503384461324",
      nsfw: false,
      name: "Stage",
      id: "835876864458489857",
      bitrate: 64000,
    },
    {
      user_limit: 0,
      type: 2,
      rtc_region: null,
      position: 2,
      permission_overwrites: [],
      parent_id: "737499503384461324",
      nsfw: false,
      name: "Voice",
      id: "853225781604646933",
      bitrate: 64000,
    },
  ],
  presences: [],
  banner: null,
  afk_timeout: 300,
  explicit_content_filter: 2,
  lazy: true,
  features: ["COMMUNITY", "NEWS"],
  premium_subscription_count: 0,
  description: null,
  region: "singapore",
  nsfw: false,
  splash: null,
  premium_tier: 0,
  system_channel_id: "737499503384461325",
  nsfw_level: 0,
  default_message_notifications: 0,
  emojis: [],
  joined_at: "2021-02-05T10:41:10.307000+00:00",
  discovery_splash: null,
  members: [
    {
      user: {
        username: "Skick",
        public_flags: 131136,
        id: "653848088280301571",
        discriminator: "4724",
        avatar: "",
      },
      roles: [],
      mute: false,
      joined_at: "2020-07-28T02:39:43.588000+00:00",
      hoisted_role: null,
      deaf: false,
    },
    {
      user: {
        username: "Test",
        id: "732441066992566304",
        discriminator: "0000",
        bot: true,
        avatar: "",
      },
      roles: [],
      mute: false,
      joined_at: "2021-02-05T10:41:10.307000+00:00",
      hoisted_role: null,
      deaf: true,
    },
  ],
  max_members: 100000,
  threads: [],
  id: "737499502763704370",
  roles: [],
  guild_hashes: {
    version: 1,
    roles: { omitted: false, hash: "OnVCeDuVZdU" },
    metadata: { omitted: false, hash: "5nPQTrBMzgo" },
    channels: { omitted: false, hash: "WCSDpgoi6A8" },
  },
  owner_id: "653848088280301571",
  application_id: null,
};

export const rawMessage = {
  type: 0,
  tts: false,
  timestamp: "2222-02-22T22:22:22.000000+00:00",
  referenced_message: null,
  pinned: false,
  mentions: [],
  mention_roles: [],
  mention_everyone: false,
  member: {
    roles: ["807199132669444117"],
    mute: false,
    joined_at: "2021-02-05T10:41:10.307000+00:00",
    hoisted_role: null,
    deaf: true,
  },
  id: "863630752813285376",
  flags: 0,
  embeds: [],
  edited_timestamp: null,
  content: "",
  components: [],
  channel_id: "737499503384461325",
  author: {
    public_flags: 0,
    username: "Test",
    id: "732441066992566304",
    discriminator: "0000",
    bot: true,
    avatar: "",
  },
  attachments: [],
  guild_id: "737499502763704370",
};

export const rawUserVoiceState = {
  member: {
    user: {
      username: "Skick",
      public_flags: 131136,
      id: "653848088280301571",
      discriminator: "4724",
      avatar: "",
    },
    roles: [],
    mute: false,
    joined_at: "2020-07-28T02:39:43.588000+00:00",
    hoisted_role: null,
    deaf: false,
  },
  user_id: "653848088280301571",
  suppress: false,
  session_id: "bac0662e110d208565d5cbd35ee2a200",
  self_video: false,
  self_mute: false,
  self_deaf: false,
  request_to_speak_timestamp: null,
  mute: false,
  guild_id: "737499502763704370",
  deaf: false,
  channel_id: "853225781604646933",
};

export const rawBotVoiceState = {
  member: {
    user: {
      username: "Test",
      id: "732441066992566304",
      discriminator: "0000",
      bot: true,
      avatar: "",
    },
    roles: [],
    mute: false,
    joined_at: "2021-02-05T10:41:10.307000+00:00",
    hoisted_role: null,
    deaf: true,
  },
  user_id: "732441066992566304",
  suppress: false,
  session_id: "b09816ae9e49bb26028d3ba8e383857b",
  self_video: false,
  self_mute: false,
  self_deaf: true,
  request_to_speak_timestamp: null,
  mute: false,
  guild_id: "737499502763704370",
  deaf: true,
  channel_id: "853225781604646933",
};

export const firstPlaylistInfo = {
  id: "PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
  thumbnail: {
    url: "https://i.ytimg.com/vi/3moLkjvhEu0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA14XKyrORIifS-TIjf9cu1Z8hDPA",
    width: 336,
    height: 188,
  },
  url: "https://www.youtube.com/playlist?list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
  title: "distube",
  total_items: 17,
  views: 1676,
  items: [
    {
      title: "Disturbed - Stricken [Official Music Video]",
      id: "3moLkjvhEu0",
      shortUrl: "https://www.youtube.com/watch?v=3moLkjvhEu0",
      url: "https://www.youtube.com/watch?v=3moLkjvhEu0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=1",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/3moLkjvhEu0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB2iwHMKdR4SeKViqLx-UR9HwOFUw",
      isLive: false,
      duration: "4:11",
    },
    {
      title: "Disturbed - Down With The Sickness [Official Music Video]",
      id: "09LTT0xwdfw",
      shortUrl: "https://www.youtube.com/watch?v=09LTT0xwdfw",
      url: "https://www.youtube.com/watch?v=09LTT0xwdfw&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=2",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/09LTT0xwdfw/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBYSeu3wpE9Ln744sGFrEYxS7lHDw",
      isLive: false,
      duration: "3:37",
    },
    {
      title: "Disturbed - Stupify [Official Music Video]",
      id: "GVcY--XzeIc",
      shortUrl: "https://www.youtube.com/watch?v=GVcY--XzeIc",
      url: "https://www.youtube.com/watch?v=GVcY--XzeIc&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=3",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/GVcY--XzeIc/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBIR2I-rPAgACGifAg7_9wwmIuyWA",
      isLive: false,
      duration: "4:07",
    },
    {
      title: "Godsmack - I Stand Alone (Official Music Video)",
      id: "OYjZK_6i37M",
      shortUrl: "https://www.youtube.com/watch?v=OYjZK_6i37M",
      url: "https://www.youtube.com/watch?v=OYjZK_6i37M&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=4",
      author: {
        url: "https://www.youtube.com/channel/UCe9rl8k6yymUeVzzXfFGWwA",
        channelID: "UCe9rl8k6yymUeVzzXfFGWwA",
        name: "Godsmack",
      },
      thumbnail:
        "https://i.ytimg.com/vi/OYjZK_6i37M/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCTJhGi36XXmWuxkWFTCIERq_4zrw",
      isLive: false,
      duration: "4:56",
    },
    {
      title: "System Of A Down - B.Y.O.B. (Official Video)",
      id: "zUzd9KyIDrM",
      shortUrl: "https://www.youtube.com/watch?v=zUzd9KyIDrM",
      url: "https://www.youtube.com/watch?v=zUzd9KyIDrM&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=5",
      author: {
        url: "https://www.youtube.com/channel/UC7-YMmnc0ppcWmio8t1WdcA",
        channelID: "UC7-YMmnc0ppcWmio8t1WdcA",
        name: "System Of A Down",
      },
      thumbnail:
        "https://i.ytimg.com/vi/zUzd9KyIDrM/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAsxmHhtE691Sh76BsF957tq-yuqg",
      isLive: false,
      duration: "4:23",
    },
    {
      title: "System Of A Down - Chop Suey! (Official Video)",
      id: "CSvFpBOe8eY",
      shortUrl: "https://www.youtube.com/watch?v=CSvFpBOe8eY",
      url: "https://www.youtube.com/watch?v=CSvFpBOe8eY&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=6",
      author: {
        url: "https://www.youtube.com/channel/UC7-YMmnc0ppcWmio8t1WdcA",
        channelID: "UC7-YMmnc0ppcWmio8t1WdcA",
        name: "System Of A Down",
      },
      thumbnail:
        "https://i.ytimg.com/vi/CSvFpBOe8eY/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBGntrlv7yGSQfPdN4bXXTUMFUxiQ",
      isLive: false,
      duration: "3:27",
    },
    {
      title: "Drowning Pool - Bodies",
      id: "04F4xlWSFh0",
      shortUrl: "https://www.youtube.com/watch?v=04F4xlWSFh0",
      url: "https://www.youtube.com/watch?v=04F4xlWSFh0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=7",
      author: {
        url: "https://www.youtube.com/channel/UCRFHKKNGdaIs9NaULSUuKGw",
        channelID: "UCRFHKKNGdaIs9NaULSUuKGw",
        name: "Drowning Pool",
      },
      thumbnail:
        "https://i.ytimg.com/vi/04F4xlWSFh0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCrnDKQ4Rfqnx9qt6FrK9FzxznshQ",
      isLive: false,
      duration: "3:40",
    },
    {
      title: "Drowning Pool - Step Up",
      id: "Co5n2RVbWM0",
      shortUrl: "https://www.youtube.com/watch?v=Co5n2RVbWM0",
      url: "https://www.youtube.com/watch?v=Co5n2RVbWM0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=8",
      author: {
        url: "https://www.youtube.com/channel/UCRFHKKNGdaIs9NaULSUuKGw",
        channelID: "UCRFHKKNGdaIs9NaULSUuKGw",
        name: "Drowning Pool",
      },
      thumbnail:
        "https://i.ytimg.com/vi/Co5n2RVbWM0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB3rdoqRQ8Nno9nXK8B8epUFiMxRQ",
      isLive: false,
      duration: "3:23",
    },
    {
      title: "Disturbed - down with the sickness",
      id: "L78yVFeyvRo",
      shortUrl: "https://www.youtube.com/watch?v=L78yVFeyvRo",
      url: "https://www.youtube.com/watch?v=L78yVFeyvRo&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=9",
      author: {
        url: "https://www.youtube.com/user/xJuliiaJewelx",
        channelID: "UCIG-qQkc8nrazBcLPIrbTPA",
        name: "xJuliiaJewelx",
      },
      thumbnail:
        "https://i.ytimg.com/vi/L78yVFeyvRo/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDadTqyq2Q_bt9_8An8XnjsZLbFPQ",
      isLive: false,
      duration: "4:39",
    },
    {
      title: "stupify - disturbed",
      id: "CQBNH3UFEC0",
      shortUrl: "https://www.youtube.com/watch?v=CQBNH3UFEC0",
      url: "https://www.youtube.com/watch?v=CQBNH3UFEC0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=10",
      author: {
        url: "https://www.youtube.com/user/disturbedrocka",
        channelID: "UC-aNyA0-LT96awZKERYCTRQ",
        name: "disturbedrocka",
      },
      thumbnail:
        "https://i.ytimg.com/vi/CQBNH3UFEC0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDymt-BEQ1pPCkJKvOcjTWfu6I2Sg",
      isLive: false,
      duration: "4:35",
    },
    {
      title: "Limp Bizkit - Break Stuff",
      id: "ZpUYjpKg9KY",
      shortUrl: "https://www.youtube.com/watch?v=ZpUYjpKg9KY",
      url: "https://www.youtube.com/watch?v=ZpUYjpKg9KY&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=11",
      author: {
        url: "https://www.youtube.com/channel/UCCndqRyI-5Zl8Mutlq71ASw",
        channelID: "UCCndqRyI-5Zl8Mutlq71ASw",
        name: "limpbizkit",
      },
      thumbnail:
        "https://i.ytimg.com/vi/ZpUYjpKg9KY/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBqjo0H2NzhILiA5XmtJlDw-6RuMg",
      isLive: false,
      duration: "2:50",
    },
    {
      title: "Limp Bizkit - Faith",
      id: "l-EdCNjumvI",
      shortUrl: "https://www.youtube.com/watch?v=l-EdCNjumvI",
      url: "https://www.youtube.com/watch?v=l-EdCNjumvI&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=12",
      author: {
        url: "https://www.youtube.com/channel/UCCndqRyI-5Zl8Mutlq71ASw",
        channelID: "UCCndqRyI-5Zl8Mutlq71ASw",
        name: "limpbizkit",
      },
      thumbnail:
        "https://i.ytimg.com/vi/l-EdCNjumvI/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAUrzUryFQPf2HdMurxsoGwzLybLQ",
      isLive: false,
      duration: "2:45",
    },
    {
      title: "Limp Bizkit- jump around",
      id: "UI-jNetj9t0",
      shortUrl: "https://www.youtube.com/watch?v=UI-jNetj9t0",
      url: "https://www.youtube.com/watch?v=UI-jNetj9t0&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=13",
      author: {
        url: "https://www.youtube.com/user/bobeen17",
        channelID: "UClDFSTgkAUvaHnvv-qw9vzw",
        name: "bobeen17",
      },
      thumbnail:
        "https://i.ytimg.com/vi/UI-jNetj9t0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCdU7MOvU96HkOY15i9Zid2aq7JUw",
      isLive: false,
      duration: "2:46",
    },
    {
      title: "Slipknot - Psychosocial [OFFICIAL VIDEO]",
      id: "5abamRO41fE",
      shortUrl: "https://www.youtube.com/watch?v=5abamRO41fE",
      url: "https://www.youtube.com/watch?v=5abamRO41fE&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=14",
      author: {
        url: "https://www.youtube.com/channel/UCOJZ1tna8yj8mAEITPkHNCQ",
        channelID: "UCOJZ1tna8yj8mAEITPkHNCQ",
        name: "Slipknot",
      },
      thumbnail:
        "https://i.ytimg.com/vi/5abamRO41fE/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBeLRAt_djqKyYG9jv-vniKG-27-g",
      isLive: false,
      duration: "5:03",
    },
    {
      title: "Disturbed - Another Way To Die [Official Music Video]",
      id: "HwELajFteTo",
      shortUrl: "https://www.youtube.com/watch?v=HwELajFteTo",
      url: "https://www.youtube.com/watch?v=HwELajFteTo&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=15",
      author: {
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        name: "Disturbed",
      },
      thumbnail:
        "https://i.ytimg.com/vi/HwELajFteTo/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAcbMwxa_WV95kQB4Kzqo-W-vZqyw",
      isLive: false,
      duration: "4:15",
    },
    {
      title: "A'lure Girls - ผักบุ้ง [HD]",
      id: "4B7H6zaeOzw",
      shortUrl: "https://www.youtube.com/watch?v=4B7H6zaeOzw",
      url: "https://www.youtube.com/watch?v=4B7H6zaeOzw&list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8&index=16",
      author: {
        url: "https://www.youtube.com/user/VertexClub7",
        channelID: "UC0qtGtAqSCgmkZFV3-5uWyA",
        name: "Movie Reac",
      },
      thumbnail:
        "https://i.ytimg.com/vi/4B7H6zaeOzw/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBFrToXZBo1cAOKFu5DKAOtsBkSwQ",
      isLive: false,
      duration: "4:01",
    },
  ],
};

export const playlistResults = {
  query: "distube",
  items: [
    {
      type: "playlist",
      id: "PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
      name: "distube",
      url: "https://www.youtube.com/playlist?list=PLkqOl2GD1Tj_STgpqmpsMjqN_2j5Rvir8",
      length: 17,
    },
    {
      type: "playlist",
      id: "PLRTLV2e_ZXmbjDnej-_gAsYPa93w3sYlr",
      name: "Distube",
      url: "https://www.youtube.com/playlist?list=PLRTLV2e_ZXmbjDnej-_gAsYPa93w3sYlr",
      length: 25,
    },
    {
      type: "playlist",
      id: "PLVdLN4Yhy71d3Nr3XXQYPsIN8m4vIej7F",
      name: "Best +100 Free Glitch Effect Footage 2021 (Noise, VHS Layer, TV Effects)",
      url: "https://www.youtube.com/playlist?list=PLVdLN4Yhy71d3Nr3XXQYPsIN8m4vIej7F",
      length: 706,
    },
    {
      type: "playlist",
      id: "PLdkO2Lq_XOx1zfzYnySSlysYv0BgW3V3l",
      name: "Distube",
      url: "https://www.youtube.com/playlist?list=PLdkO2Lq_XOx1zfzYnySSlysYv0BgW3V3l",
      length: 9,
    },
    {
      type: "playlist",
      id: "PLbLeA7W1w2T5Kg431BCMvUfTCyWfaKn4S",
      name: "Discord Music Bot Tutorial",
      url: "https://www.youtube.com/playlist?list=PLbLeA7W1w2T5Kg431BCMvUfTCyWfaKn4S",
      length: 17,
    },
    {
      type: "playlist",
      id: "PL7cOvxWH-wycFYfTcHIliPxSoRajT8FWp",
      name: "Best Disturbed Songs",
      url: "https://www.youtube.com/playlist?list=PL7cOvxWH-wycFYfTcHIliPxSoRajT8FWp",
      length: 68,
    },
    {
      type: "playlist",
      id: "PLC08AD2C2BAB0F8F6",
      name: "Disturbed youtube mix",
      url: "https://www.youtube.com/playlist?list=PLC08AD2C2BAB0F8F6",
      length: 75,
    },
    {
      type: "playlist",
      id: "PLLsdMJN8M0wQ2th-U85wwGo85a6Nm_-xi",
      name: "Shinedown, Volbeat, 5FDP, Disturbed, Godsmack, Etc",
      url: "https://www.youtube.com/playlist?list=PLLsdMJN8M0wQ2th-U85wwGo85a6Nm_-xi",
      length: 229,
    },
    {
      type: "playlist",
      id: "PLJbLehBWfm_dbUoHsMLeQBPPJXip89kyG",
      name: "디스코드 봇 만들기 (기본)",
      url: "https://www.youtube.com/playlist?list=PLJbLehBWfm_dbUoHsMLeQBPPJXip89kyG",
      length: 13,
    },
    {
      type: "playlist",
      id: "PLllWUr3O6d5g2ucR2RdIeCfK1ziYKoXJE",
      name: "Distube good",
      url: "https://www.youtube.com/playlist?list=PLllWUr3O6d5g2ucR2RdIeCfK1ziYKoXJE",
      length: 64,
    },
  ],
  results: 74,
};

export const videoResults = {
  query: "distube",
  items: [
    {
      type: "video",
      name: "Discord.js x Distube | Play, Stop, Skip Commands (Part 1) (2021+) [Episode #16]",
      id: "tbPqM6JcGA4",
      url: "https://www.youtube.com/watch?v=tbPqM6JcGA4",
      thumbnail:
        "https://i.ytimg.com/vi/tbPqM6JcGA4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBGzjqv86A0ml10BXDIVWiTQhhyPQ",
      isLive: false,
      author: {
        name: "CougHyyee",
        channelID: "UCnkI1CiXpdQeibcwtCtVvIQ",
        url: "https://www.youtube.com/channel/UCnkI1CiXpdQeibcwtCtVvIQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 1710,
      duration: "16:44",
      uploadedAt: "3 months ago",
    },
    {
      type: "video",
      name: "Discord.js (v12) BOT | Most easiest Music Bot | filters, seek, play, skip, stop | distube | 1/3",
      id: "lzZU-8FU2wQ",
      url: "https://www.youtube.com/watch?v=lzZU-8FU2wQ",
      thumbnail:
        "https://i.ytimg.com/vi/lzZU-8FU2wQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD3pBo_uShS_7KuxFy3phF3xx-edw",
      isLive: false,
      author: {
        name: "Tomato6966",
        channelID: "UC1AgotpFHNhzolUtAjPgZqQ",
        url: "https://www.youtube.com/channel/UC1AgotpFHNhzolUtAjPgZqQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLSNDx98wsvw3WTJHaZs2NCCQTGFl1KC0xautdSDdA=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLSNDx98wsvw3WTJHaZs2NCCQTGFl1KC0xautdSDdA=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 4030,
      duration: "1:10:25",
      uploadedAt: "7 months ago",
    },
    {
      type: "video",
      name: "Disturbed - Stricken [Video]",
      id: "I77mjesUbkw",
      url: "https://www.youtube.com/watch?v=I77mjesUbkw",
      thumbnail:
        "https://i.ytimg.com/vi/I77mjesUbkw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAaztN4uv4H9-Bnw5G0XHaicLZgmg",
      isLive: false,
      author: {
        name: "Disturbed",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 56632348,
      duration: "4:11",
      uploadedAt: "11 years ago",
    },
    {
      type: "video",
      name: "Disturbed - Down With The Sickness [Official Music Video]",
      id: "09LTT0xwdfw",
      url: "https://www.youtube.com/watch?v=09LTT0xwdfw",
      thumbnail:
        "https://i.ytimg.com/vi/09LTT0xwdfw/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCPFLfKQZ6EILrXEiox5oMcaxvFow",
      isLive: false,
      author: {
        name: "Disturbed",
        channelID: "UCveWMJeHgcIUPMnFzd7Vxjg",
        url: "https://www.youtube.com/channel/UCveWMJeHgcIUPMnFzd7Vxjg",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLTZnr3YBFhWGU14FhE26Dd4d2Kd8bhQ8iNMCxkI=s88-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: ["Official Artist Channel"],
        verified: true,
      },
      description: null,
      views: 137706960,
      duration: "3:37",
      uploadedAt: "11 years ago",
    },
    {
      type: "video",
      name: "Discord.js x Distube | Queue & Skip Commands (Part 2) (2021+) [Episode #16]",
      id: "ylXL2Grsplc",
      url: "https://www.youtube.com/watch?v=ylXL2Grsplc",
      thumbnail:
        "https://i.ytimg.com/vi/ylXL2Grsplc/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDZ1WslIzG7iR9uYw1qftQJGz_dVA",
      isLive: false,
      author: {
        name: "CougHyyee",
        channelID: "UCnkI1CiXpdQeibcwtCtVvIQ",
        url: "https://www.youtube.com/channel/UCnkI1CiXpdQeibcwtCtVvIQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLQoucOrZF-ODh_RYBz3RZdmAFEyPBXuBW3ePwec=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 718,
      duration: "8:08",
      uploadedAt: "2 months ago",
    },
    {
      type: "video",
      name: "[NEW] DISCORD.JS MUSIC BOT! (UPDATED)",
      id: "Zxx0AQZ29lM",
      url: "https://www.youtube.com/watch?v=Zxx0AQZ29lM",
      thumbnail:
        "https://i.ytimg.com/vi/Zxx0AQZ29lM/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB4t_w4uOQOVPq6d31aV62pFxru6Q",
      isLive: false,
      author: {
        name: "DashCruft",
        channelID: "UCGfLATfpHApnScvMr9dXd1g",
        url: "https://www.youtube.com/channel/UCGfLATfpHApnScvMr9dXd1g",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLT6iwnUfxrXKrzPgfYEk9H-1K5ALj6Wr8IFnxvOKw=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLT6iwnUfxrXKrzPgfYEk9H-1K5ALj6Wr8IFnxvOKw=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 32245,
      duration: "13:31",
      uploadedAt: "5 months ago",
    },
    {
      type: "video",
      name: "How to setup DisTube bot discord very easily on your discord server | Music & Fun",
      id: "oqpgPWSOHdM",
      url: "https://www.youtube.com/watch?v=oqpgPWSOHdM",
      thumbnail:
        "https://i.ytimg.com/vi/oqpgPWSOHdM/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBIDFAniSRLG21ux0JjNek6DEMHMw",
      isLive: false,
      author: {
        name: "Roduz",
        channelID: "UCjnUiHCUWjwx_cizD4JYpjQ",
        url: "https://www.youtube.com/channel/UCjnUiHCUWjwx_cizD4JYpjQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLSDlEFv1TLkFq47l2X3_I2D1koTry6BKI35TmmH=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLSDlEFv1TLkFq47l2X3_I2D1koTry6BKI35TmmH=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 1061,
      duration: "8:09",
      uploadedAt: "5 months ago",
    },
    {
      type: "video",
      name: "Distube Music Bot ytdl-core Status Code 404 ,429 Error Fixed  | Advance Discord Distube Music Bot",
      id: "9bZGT9frKLw",
      url: "https://www.youtube.com/watch?v=9bZGT9frKLw",
      thumbnail:
        "https://i.ytimg.com/vi/9bZGT9frKLw/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCk5S5xyFVReGcCdPV_gDPK60lUMQ",
      isLive: false,
      author: {
        name: "Tech Boy Gaming",
        channelID: "UCINCfgiBYCykOemiuVhqtIQ",
        url: "https://www.youtube.com/channel/UCINCfgiBYCykOemiuVhqtIQ",
        bestAvatar: {
          url: "https://yt3.ggpht.com/ytc/AKedOLScR4eUWjJt0bHTftgQ_lf7skYCWulN-Jh-3BtXQQ=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/ytc/AKedOLScR4eUWjJt0bHTftgQ_lf7skYCWulN-Jh-3BtXQQ=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 949,
      duration: "7:36",
      uploadedAt: "2 weeks ago",
    },
    {
      type: "video",
      name: "How to setup PyQuantum giveaway feature in Discord | Distube | Bot Setup #2",
      id: "eBgS5KgxA1E",
      url: "https://www.youtube.com/watch?v=eBgS5KgxA1E",
      thumbnail:
        "https://i.ytimg.com/vi/eBgS5KgxA1E/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA-8FbPrnnCu3bTYclM3vscU37xqQ",
      isLive: false,
      author: {
        name: "Distube ",
        channelID: "UCaD6sK5RA_8dLuMoD22Xs0A",
        url: "https://www.youtube.com/channel/UCaD6sK5RA_8dLuMoD22Xs0A",
        bestAvatar: {
          url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 188,
      duration: "2:29",
      uploadedAt: "3 weeks ago",
    },
    {
      type: "video",
      name: "How to setup Server Stats bot in Discord | Distube | Bot Setup #1",
      id: "G8jz3tmGznE",
      url: "https://www.youtube.com/watch?v=G8jz3tmGznE",
      thumbnail:
        "https://i.ytimg.com/vi/G8jz3tmGznE/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCs-T5gu7Kyb_DFe-7fe3zB3ZP1SQ",
      isLive: false,
      author: {
        name: "Distube ",
        channelID: "UCaD6sK5RA_8dLuMoD22Xs0A",
        url: "https://www.youtube.com/channel/UCaD6sK5RA_8dLuMoD22Xs0A",
        bestAvatar: {
          url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
          width: 68,
          height: 68,
        },
        avatars: [
          {
            url: "https://yt3.ggpht.com/HEGPbCCVxh8OUbrh2-peQdA92_cz4r0ecZXlprT9P426C_TKt6gH5i4ULNFOws4WPG24R3mxLw=s68-c-k-c0x00ffffff-no-rj",
            width: 68,
            height: 68,
          },
        ],
        ownerBadges: [],
      },
      description: null,
      views: 56,
      duration: "2:27",
      uploadedAt: "3 weeks ago",
    },
  ],
  results: 2420,
};
